nelmio_api_doc:
    documentation:
        info:
            title: App
            description: App test task
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
            security:
                - Bearer: []
        paths:
            /api/v1/auth:
                post:
                    tags:
                        - Authentication
                    summary: Login
                    requestBody:
                        content:
                            application/json:
                                schema:
                                    properties:
                                        login:
                                            type: string
                                            example: admin@test.local
                                        password:
                                            type: string
                                            example: 123456
                                    type: object
                    responses:
                        '200':
                            description: OK
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                        '401':
                            description: Invalid credentials
                        '400':
                            description: Invalid JSON.
                    security: []

    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!(/doc|/doc\.json)$) # Accepts routes under /api except /api/doc
