services:
  php:
    container_name: 'php'
    build:
      context: ./.docker/php
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - ./:/lk
    working_dir: /lk
    networks:
      - lk

  nginx:
    container_name: 'nginx'
    image: nginx:1.25-alpine
    ports:
      - "8888:80"
    volumes:
      - ./:/lk
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    networks:
      - lk

#  db:
#    container_name: 'db'
#    image: percona:8
#    ports:
#      - "3306:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    environment:
#      MYSQL_USER: root
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: lk
#    networks:
#      - lk

  db:
    container_name: 'db'
    image: postgres:16.2-alpine
    ports:
       - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: lk
    volumes:
      - db_data_pgl:/var/lib/postgresql/data:rw
    networks:
      - lk

volumes:
#  db_data:
  db_data_pgl:

networks:
  lk: