controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: App\Kernel
    type: attribute

api_v1_controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller\Api\V1
    type: attribute

api_auth:
    path: /api/v1/auth

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }